import { StepDefinition } from './types';

export const ACTIVATION_STEPS: StepDefinition[] = [
  {
    id: 0,
    key: 'welcome',
    title: 'Personalização',
    description: 'Vamos personalizar sua loja.',
    route: null,
    duration: '1min',
    skippable: false,
    essential: true,
    detection: { type: 'manual' },
  },
  {
    id: 1,
    key: 'company',
    title: 'Dados da Empresa',
    description: 'Configure o nome e dados da sua empresa.',
    route: '/configuracoes',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'field_filled', entity: 'company', fields: ['name'] },
  },
  {
    id: 2,
    key: 'categories',
    title: 'Categorias',
    description: 'Organize seus produtos por tipo.',
    route: '/categorias',
    duration: '1min',
    skippable: true,
    essential: false,
    detection: { type: 'entity_exists', entity: 'category', min: 1 },
  },
  {
    id: 3,
    key: 'product',
    title: 'Primeiro Produto',
    description: 'Cadastre seu primeiro produto para vender.',
    route: '/produtos',
    duration: '2min',
    skippable: false,
    essential: true,
    detection: { type: 'entity_exists', entity: 'product', min: 1 },
  },
  {
    id: 4,
    key: 'customer',
    title: 'Cliente',
    description: 'Cadastre um cliente ou use o Consumidor Final.',
    route: '/clientes',
    duration: '1min',
    skippable: true,
    essential: false,
    detection: { type: 'entity_exists', entity: 'customer', min: 1 },
  },
  {
    id: 5,
    key: 'cash_register',
    title: 'Caixa',
    description: 'Abra o caixa para começar a vender.',
    route: '/caixas',
    duration: '30s',
    skippable: true,
    essential: true,
    detection: { type: 'session_active', entity: 'cash_session', status: 'open' },
  },
  {
    id: 6,
    key: 'first_sale',
    title: 'Primeira Venda',
    description: 'Faça sua primeira venda no PDV.',
    route: '/pdv',
    duration: '3min',
    skippable: false,
    essential: true,
    detection: { type: 'entity_exists', entity: 'sale', min: 1 },
  },
  {
    id: 7,
    key: 'celebration',
    title: 'Pronto!',
    description: 'Sua loja está funcionando!',
    route: null,
    duration: '10s',
    skippable: false,
    essential: true,
    detection: { type: 'manual' },
  },
];

export const FINANCIAL_STEPS: StepDefinition[] = [
  {
    id: 0,
    key: 'caixas',
    title: 'Gestão de Caixas',
    description: 'Entenda como gerenciar seus caixas.',
    route: '/caixas',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
  {
    id: 1,
    key: 'recebimentos',
    title: 'Recebimentos e Pagamentos',
    description: 'Controle entradas e saídas.',
    route: '/financeiro',
    duration: '3min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
  {
    id: 2,
    key: 'fornecedores',
    title: 'Fornecedores',
    description: 'Cadastre seus fornecedores.',
    route: '/fornecedores',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'entity_exists', entity: 'supplier', min: 1 },
  },
  {
    id: 3,
    key: 'plano_contas',
    title: 'Plano de Contas',
    description: 'Organize suas categorias financeiras.',
    route: '/plano-contas',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
  {
    id: 4,
    key: 'fluxo_caixa',
    title: 'Fluxo de Caixa',
    description: 'Veja a projeção financeira da sua empresa.',
    route: '/fluxo-caixa',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
  {
    id: 5,
    key: 'dre',
    title: 'DRE',
    description: 'Acompanhe o resultado da sua empresa.',
    route: '/dre',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
  {
    id: 6,
    key: 'ia_gerente',
    title: 'IA Gerente',
    description: 'Conheça seu gerente inteligente.',
    route: '/ia-gerente',
    duration: '2min',
    skippable: true,
    essential: false,
    detection: { type: 'manual' },
  },
];

export function getStepsForPhase(phase: string): StepDefinition[] {
  return phase === 'financial' ? FINANCIAL_STEPS : ACTIVATION_STEPS;
}

export function getStepByKey(key: string): StepDefinition | undefined {
  return [...ACTIVATION_STEPS, ...FINANCIAL_STEPS].find(s => s.key === key);
}
